# version: "3.9"
services:
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis-data:/data:rw
    ports:
      - "6379"
    networks:
      - app-tier
  web:
    build: .
    volumes:
      - ./bot.db:/app/bot.db:rw
      - ./log.txt:/app/log.txt:rw
    depends_on:
      - redis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
